# Generated by Django 3.2.12 on 2022-04-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Basics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='DOB',
        ),
    ]
